version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 1535:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network

  php:
    build: .
    container_name: php
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: teste
      MYSQL_PASSWORD: t3s.t3
    volumes:
      - .mysql:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge