name: Enviar alterações para branch MAIN
on:
  push:
    branches:
      - pipeline
jobs:
  # test:
  #   runs-on: ubuntu-latest   
  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Buildando e subindo os containers
  #     run: docker compose up -d --build

  #   - name: instalando composer
  #     run: docker compose exec php sh -c "composer install --no-interaction --no-plugins --no-scripts"

  #   - name: Executando os testes do laravel
  #     run: docker compose exec php php artisan test --testsuite=Unit

  #   - name: Derrubando o docker-compose
  #     if: always()
  #     run: docker compose down

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "Inicia deploy para produção ..."

      - uses: actions/checkout@v4

      # - name: Configura o git
      #   run: |
      #     git config --global user.name "${{secrets.GH_NAME}}"
      #     git config --global user.email "${{secrets.GH_EMAIL}}"

      - name: verifica as branches
        run: git branch

      - name: Baixa branches novas no projeto
        run: git fetch

      - name: Dar checkout para a branch master
        run: git checkout master

      - name: Baixa branches novas no projeto
        run: git fetch
      
      - name: verifica as branches
        run: git branch

      - name: Realiza merge branch pipeline com a master
        run: git merge pipeline --allow-unrelated-histories

      - name: Sobe alterações/atualizações para a master
        run: git push master

    
