name: Enviar alterações para branch MAIN
on:
  push:
    branches:
      - pipeline
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Buildando e subindo os containers
      run: docker compose up -d --build

    - name: Executando os testes do laravel
      run: docker compose exec -it php php artisan test

    - name: Derrubando o docker-compose
      if: always()
      run: docker compose down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "Inicia deploy para produção ..."
      
      - name: Liberando acesso ao repositório
        run: actions/checkout@v4

      - name: Configura o git
        run: |
          git config --global user.name "${{secrets.GH_NAME}}"
          git config --global user.email "${{secrets.GH_EMAIL}}"

      - name: Baixa branches novas no projeto
        run: git fetch

      - name: Dar checkout para a branch master
        run: git checkout master

      - name: Realiza merge com a pipeline
        run: git merge origin pipeline

      - name: Subindo alterações para a master
        run: git push origin mater

    
